"""One place that reads config/, so no module ever embeds a tunable.

Both files are cached after the first read -- they are small, and the
simulation calls into them thousands of times. Tests that need to try a
different rule set call :func:`reload`.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
RULES_PATH = ROOT / "config" / "rules.yaml"
LEGAL_PATH = ROOT / "config" / "legal.yaml"
SUPPLIER_PATH = ROOT / "config" / "supplier.yaml"
MESSAGES_PATH = ROOT / "config" / "messages.yaml"
REPLIES_PATH = ROOT / "config" / "replies.yaml"
LEARNED_RECOVERY_PATH = ROOT / "config" / "learned_recovery.yaml"


@lru_cache(maxsize=1)
def rules() -> dict[str, Any]:
    """Ladder timings, score weights, stopping limits."""
    return yaml.safe_load(RULES_PATH.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def legal() -> dict[str, Any]:
    """MSMED Act and Income Tax figures. Simplified, as of Aug 2026, not legal advice."""
    return yaml.safe_load(LEGAL_PATH.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def supplier() -> dict[str, Any]:
    """Our own business identity. Needed to file anything in our own name."""
    return yaml.safe_load(SUPPLIER_PATH.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def messages() -> dict[str, Any]:
    """Message scaffolding: tone, mock drafts, fallback wording, threat words.

    Carries no legal prose and no legal figures -- those arrive already
    rendered from config/legal.yaml. A test enforces it.
    """
    return yaml.safe_load(MESSAGES_PATH.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def replies() -> dict[str, Any]:
    """Canned buyer replies for mock mode, keyed by fixture name."""
    return yaml.safe_load(REPLIES_PATH.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def learned_recovery() -> dict[str, Any]:
    """Fitted per-(quadrant, action) recovery posteriors.

    Generated by scripts/fit_recovery.py; provenance in docs/learning_data.md.
    Read only when config/rules.yaml's learning.enabled is true, and only
    through engine/learning.py. Raises FileNotFoundError if the file was never
    generated -- engine/learning.py turns that into a clear startup error.
    """
    return yaml.safe_load(LEARNED_RECOVERY_PATH.read_text(encoding="utf-8"))


def ev_mode_on(config: dict[str, Any] | None = None) -> bool:
    """True when config/rules.yaml's brain.ev_mode selects the EV path.

    YAML parses a bare ``on`` / ``off`` as a boolean, while the simulator and
    the brain's own tests set the string ``"on"`` explicitly -- both spellings
    mean on, and anything else (``off``, ``False``, absent) means off. One
    place decides this so engine/brain.py and engine/learning.py cannot read
    the same key two different ways.
    """
    settings = config if config is not None else rules()
    raw = settings.get("brain", {}).get("ev_mode", False)
    return raw is True or str(raw).strip().lower() == "on"


def reload() -> None:
    """Drop the cached config. For tests that edit the YAML on disk."""
    rules.cache_clear()
    legal.cache_clear()
    supplier.cache_clear()
    messages.cache_clear()
    replies.cache_clear()
    learned_recovery.cache_clear()
