"""One place that reads config/, so no module ever embeds a tunable.

Both files are cached after the first read -- they are small, and the
simulation calls into them thousands of times. Tests that need to try a
different rule set call :func:`reload`.
"""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager
from contextvars import ContextVar
from functools import lru_cache
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
RULES_PATH = ROOT / "config" / "rules.yaml"
LEGAL_PATH = ROOT / "config" / "legal.yaml"
SUPPLIER_PATH = ROOT / "config" / "supplier.yaml"
MESSAGES_PATH = ROOT / "config" / "messages.yaml"
REPLIES_PATH = ROOT / "config" / "replies.yaml"
LEARNED_RECOVERY_PATH = ROOT / "config" / "learned_recovery.yaml"


@lru_cache(maxsize=1)
def rules() -> dict[str, Any]:
    """Ladder timings, score weights, stopping limits."""
    return yaml.safe_load(RULES_PATH.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def legal() -> dict[str, Any]:
    """MSMED Act and Income Tax figures. Simplified, as of Aug 2026, not legal advice."""
    return yaml.safe_load(LEGAL_PATH.read_text(encoding="utf-8"))


#: SaaS: the supplier identity of the business (tenant) an API request is
#: acting for. None everywhere else -- the simulator, main.py and every test
#: read config/supplier.yaml exactly as before.
_supplier_override: ContextVar[dict[str, Any] | None] = ContextVar(
    "supplier_override", default=None)


def supplier() -> dict[str, Any]:
    """Our own business identity. Needed to file anything in our own name.

    Returns the tenant's identity inside supplier_context() (the SaaS API, one
    business per request), otherwise config/supplier.yaml.
    """
    override = _supplier_override.get()
    return override if override is not None else _supplier_file()


@lru_cache(maxsize=1)
def _supplier_file() -> dict[str, Any]:
    return yaml.safe_load(SUPPLIER_PATH.read_text(encoding="utf-8"))


# Kept so existing callers of supplier.cache_clear() (reload(), tests) work.
supplier.cache_clear = _supplier_file.cache_clear  # type: ignore[attr-defined]


@contextmanager
def supplier_context(profile: dict[str, Any]) -> Iterator[None]:
    """Make `profile` (same shape as config/supplier.yaml) the supplier for the
    duration of the block -- writer sign-offs and Samadhaan drafts then carry
    the tenant's own name and Udyam number, not the demo placeholder."""
    token = _supplier_override.set(profile)
    try:
        yield
    finally:
        _supplier_override.reset(token)


@lru_cache(maxsize=1)
def messages() -> dict[str, Any]:
    """Message scaffolding: tone, mock drafts, fallback wording, threat words.

    Carries no legal prose and no legal figures -- those arrive already
    rendered from config/legal.yaml. A test enforces it.
    """
    return yaml.safe_load(MESSAGES_PATH.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def replies() -> dict[str, Any]:
    """Canned buyer replies for mock mode, keyed by fixture name."""
    return yaml.safe_load(REPLIES_PATH.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def learned_recovery() -> dict[str, Any]:
    """Fitted per-(quadrant, action) recovery posteriors.

    Generated by scripts/fit_recovery.py; provenance in docs/learning_data.md.
    Read only when config/rules.yaml's learning.enabled is true, and only
    through engine/learning.py. Raises FileNotFoundError if the file was never
    generated -- engine/learning.py turns that into a clear startup error.
    """
    return yaml.safe_load(LEARNED_RECOVERY_PATH.read_text(encoding="utf-8"))


def ev_mode_on(config: dict[str, Any] | None = None) -> bool:
    """True when config/rules.yaml's brain.ev_mode selects the EV path.

    YAML parses a bare ``on`` / ``off`` as a boolean, while the simulator and
    the brain's own tests set the string ``"on"`` explicitly -- both spellings
    mean on, and anything else (``off``, ``False``, absent) means off. One
    place decides this so engine/brain.py and engine/learning.py cannot read
    the same key two different ways.
    """
    settings = config if config is not None else rules()
    raw = settings.get("brain", {}).get("ev_mode", False)
    return raw is True or str(raw).strip().lower() == "on"


def reload() -> None:
    """Drop the cached config. For tests that edit the YAML on disk."""
    rules.cache_clear()
    legal.cache_clear()
    supplier.cache_clear()
    messages.cache_clear()
    replies.cache_clear()
    learned_recovery.cache_clear()
